# Generated by Django 5.2.11 on 2026-02-11 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='education_level',
            field=models.CharField(blank=True, choices=[('School', 'School'), ('Undergraduate', 'Undergraduate'), ('Postgraduate', 'Postgraduate'), ('Other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_category',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
