# Generated by Django 5.2.11 on 2026-02-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_quiz_question_useranswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='time_taken',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
