# Generated by Django 5.2.11 on 2026-02-27 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_quiz_percentage_quiz_score_quiz_time_taken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='percentage',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='score',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='time_taken',
        ),
    ]
