# Generated by Django 5.2.11 on 2026-02-27 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_remove_quiz_percentage_remove_quiz_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='correct_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quiz',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='score_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='quiz',
            name='time_taken',
            field=models.IntegerField(default=0),
        ),
    ]
