# Generated by Django 5.2.11 on 2026-02-27 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_quiz_correct_answers_quiz_is_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='correct_answers',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='score_percentage',
        ),
        migrations.AddField(
            model_name='quiz',
            name='percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='time_taken',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
