# Generated by Django 5.2.11 on 2026-03-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0007_question_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='status',
            field=models.CharField(default='in_progress', max_length=20),
        ),
    ]
